
  <!-- General JS Scripts -->
  <script src="public/js/jquery.min.js"></script>
  <script src="public/js/popper.js"></script>
  <script src="public/js/tooltip.js"></script>
  <script src="public/js/bootstrap/js/bootstrap.min.js"></script>
  <script src="public/js/nicescroll/jquery.nicescroll.min.js"></script>
  <script src="public/js/moment.min.js"></script>
  <script src="public/js/stisla.js"></script>
  <script src="/public/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
  
  <!-- JS Libraies -->

  <!-- Page Specific JS File -->
  
  <!-- Template JS File -->
  <script src="public/js/scripts.js"></script>
  <script src="public/js/custom.js"></script>
</body>
</html>