<!-- General JS Scripts -->
<script src="/public/js/jquery.min.js"></script>
<script src="/public/js/popper.js"></script>
<script src="/public/js/tooltip.js"></script>
<script src="/public/js/bootstrap/js/bootstrap.min.js"></script>
<script src="/public/nicescroll/jquery.nicescroll.min.js"></script>
<script src="/public/js/moment.min.js"></script>
<script src="/public/js/stisla.js"></script>
<script src="/public/bootstrap-daterangepicker/bootstrap-timepicker.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js'></script>
<!-- JS Libraies -->

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="/public/js/scripts.js"></script>
<script src="/public/js/custom.js"></script>
<script>
  for (var __i = 0; __i < commands.length; __i++) {
    commands[__i]();
  }
</script>
</body>

</html>