<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title><?= $title?></title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="public/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="public/fontawesome/css/all.min.css">
  <link rel="stylesheet" href="public/bootstrap-timepicker/css/bootstrap-timepicker.min.css">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="public/bootstrap-social/bootstrap-social.css">

  <!-- Template CSS -->
  <link rel="stylesheet" href="public/css/style.css">
  <link rel="stylesheet" href="public/css/components.css">
  <link rel="stylesheet" href="public/select2/dist/css/select2.min.css">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>

<!-- /END GA --></head>
