<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title><?= $title?></title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="/public/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/public/fontawesome/css/all.min.css">
  <link rel="stylesheet" href="/public/bootstrap-social/bootstrap-social.css">


  <link rel="stylesheet" href="/public/css/components.css">

  <link rel="stylesheet" href="/public/bootstrap-timepicker/css/bootstrap-timepicker.min.css">
  <link rel="stylesheet" href="/public/select2/dist/css/select2.min.css">

  <link rel="stylesheet" href="/public/css/style.css">

</head>
