<?php

$statusClass = $work->getWorkStatus() === "planning" ? "info" : ($work->getWorkStatus() === "doing" ? "warning" : "success" )
?>

<tr>
    <td class="p-0 text-center">
        <div class="custom-checkbox custom-control">
            <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-<?= $work->getId() ?>">
            <label for="checkbox-<?= $work->getId() ?>" class="custom-control-label">&nbsp;</label>
        </div>
    </td>
    <td><?= $work->getWorkName() ?></td>
    <td>
        <?= $work->getWorkContent() ?>
    </td>
    <td><?= $work->getWorkStartDate() ?></td>

    <td><?= $work->getWorkEndDate() ?></td>
    <td>
        <div class="badge badge-<?= $statusClass?>"><?= $work->getWorkStatus() ?></div>
    </td>
    <td><a href="#" class="btn btn-secondary">Detail</a></td>
</tr>