<?php

use MyTodoList\Reponsetories\MyRepo;
use MyTodoList\Reponsetories\WorksRepo;


?>
<div class="main-content px-0">
    <div class="container">
        <section class="section">
            <div class="section-header">
                <h1>Works</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="/my-works">works manager</a></div>
               
                </div>
            </div>
            <div id='calendar'></div>

        </section>
    </div>
</div>

<script>
    commands.push(function() {
        var json = <?= json_encode($myWorks) ?>;
        $('#calendar').fullCalendar({
            timeFormat: 'H:mm',
            eventRender: function(event, element) {
                element.find('.fc-title').html(event.title);
            },
            events: json,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,basicWeek,basicDay'
            }
        });
    });
</script>