<?php
  use MyTodoList\Reponsetories\WorksRepo;
?>
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1><?= $title ?></h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="/">Calender</a></div>
                <div class="breadcrumb-item"><a href="/my-works">works manager</a></div>
                <div class="breadcrumb-item"><?= $title ?></div>
            </div>
        </div>

        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <div class="card-header">
                            <h4>Work Details</h4>
                        </div>

                        <div class="card-body">
                            <form method="post" action="/my-works/<?= strtolower($title) ?>?id=<?=$data['id'] ?>">

                                <div class="form-group">
                                    <label for="work_name">Work Name</label>
                                    <input type="text" value="<?= isset($data['work_name'])  ? $data['work_name'] : "" ?>" id="work_name" name="work_name" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="work_content">Work Content</label>
                                    <textarea id="work_content" name="work_content" class="form-control"><?= isset($data['work_name'])  ? $data['work_name'] : "" ?></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="work_start_date">Work Start Date</label>
                                    <input type="datetime-local" id="work_start_date" name="work_start_date" value="<?= isset($data['work_start_date'])  ? $data['work_start_date'] : "" ?>" class="form-control datepicker" required>
                                </div>
                                <div class="form-group">
                                    <label for="work_end_date">Work End Date</label>
                                    <input type="datetime-local"  id="work_end_date" name="work_end_date" value="<?= isset($data['work_end_date'])  ? $data['work_end_date'] : "" ?>" class="form-control datepicker" required>
                                </div>
                                <div class="form-group">
                                    <label for="work_status">Work Status</label>
                                    <select id="work_status" name="work_status" class="form-control">
                                        <?php
                                        foreach (WorksRepo::ARR_STATUS as $status) :
                                            $selected = "";
                                            if (!empty($data['work_status']) && $status == $data['work_status']) {
                                                $selected = "selected";
                                            }
                                        ?>
                                            <option <?= $selected ?> value="<?= $status  ?>"><?= ucfirst($status)  ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary"><?= $title ?></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
