<?php

use MyTodoList\Reponsetories\MyRepo;
use MyTodoList\Reponsetories\WorksRepo;

?>
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Works</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item">Table</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Table</h2>
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <div class="card-header flex-column">
                            <div class='w-100 mb-2'>
                                <h4><?= isset($time) ? $time : "" ?></h4>
                            </div>
                            <div class="row ">
                                <form name="formSearch">
                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <input id="txtContent" name="txtContent" value="<?= isset($paramsSearch['txtContent']) ? $paramsSearch['txtContent'] : "" ?>" type="text" class="form-control" placeholder="Name,Content,Id">
                                        </div>
                                        <div class="col-sm-3">
                                            <input id="slcStartDate" name="slcStartDate" value="<?= isset($paramsSearch['slcStartDate']) ? $paramsSearch['slcStartDate'] : "" ?>" type="date" class="form-control">
                                        </div>
                                        <div class="col-sm-3">
                                            <input id="slcEndDate" name="slcEndDate" value="<?= isset($paramsSearch['slcEndDate']) ? $paramsSearch['slcEndDate'] : "" ?>" type="date" class="form-control">
                                        </div>
                                        <div class="col-sm-2">
                                            <select id="slcStatus" name="slcStatus" class="form-control">
                                                <option value="">All Status</option>
                                                <?php
                                                foreach (WorksRepo::ARR_STATUS as $status) :
                                                    $selected = "";
                                                    if (!empty($paramsSearch['work_status']) && $status == $paramsSearch['work_status']) {
                                                        $selected = "selected";
                                                    }
                                                ?>
                                                    <option <?= $selected ?> value="<?= $status  ?>"><?= ucfirst($status)  ?></option>
                                                <?php endforeach ?>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                                    </div>
                                </form>




                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th>
                                            <div class="custom-checkbox custom-control">
                                                <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all">
                                                <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                                            </div>
                                        </th>
                                        <th>Task Name</th>
                                        <th>Content</th>
                                        <th>Start Date</th>
                                        <th>End Date</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    <?php
                                    if (!empty($myWorks)) {
                                        foreach ($myWorks as $work) {
                                            $this->getView(['work' => $work], "works/component/works");
                                        }
                                    }
                                    ?>
                                </table>
                                <?= MyRepo::paging($totalPages, $currentPage, "") ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</div>