<?php


use MyTodoList\Reponsetories\WorksRepo;

?>
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Works</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item">Table</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Table</h2>
            <p class="section-lead">Example of some Bootstrap table components.</p>
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <div class="card-header flex-column">
                            <div class='w-100 mb-2'>
                                <h4><?= isset($time) ? $time : "" ?></h4>
                            </div>
                            <div class="card-header-form justify-content-start w-100">
                                <form name="formSearch" class="d-flex justify-content-between" method="post">
                                    <div class="form-group">
                                        <input id="txtContent" name="txtContent" type="text" value="<?= isset($paramsSearch['txtContent']) ? $paramsSearch['txtContent'] : "" ?>" class="form-control" placeholder="name, content">
                                    </div>
                                    <div class="form-group d-flex">
                                        <label>Date Range Picker</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-calendar"></i>
                                                </div>
                                            </div>
                                            <input id="slcDateTime" name="slcDateTime" type="text" class="form-control daterange-cus">
                                        </div>
                                    </div>

                                    <div class="form-group d-flex">
                                        <label>Status</label>
                                        <select id="slcStatus" name="slcStatus" class="form-control selectric">
                                            <option value="">All status</option>
                                            <?php
                                            foreach (WorksRepo::ARR_STATUS as $status) :
                                                $selected = "";
                                                if (!empty($paramsSearch['slcStatus']) && $status == $paramsSearch['slcStatus']) {
                                                    $selected = "selected";
                                                }
                                            ?>
                                                <option <?= $selected ?> value="<?= $status  ?>"><?= ucfirst($status)  ?></option>
                                            <?php endforeach ?>
                                        </select>
                                    </div>
                                    <button type="submit">submit</button>

                                </form>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th>
                                            <div class="custom-checkbox custom-control">
                                                <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all">
                                                <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                                            </div>
                                        </th>
                                        <th>Task Name</th>
                                        <th>Content</th>
                                        <th>Start Date</th>
                                        <th>End Date</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    <?php
                                    if (!empty($myWorks)) {
                                        foreach ($myWorks as $work) {
                                            $this->getView(['work' => $work], "works/component/works");
                                        }
                                    }
                                    ?>



                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>